[package]
name = "The Crafting Framework"
description = "The Crafting Framework is library that allows modders to quickly and easily implement complex crafting mechanics in Morrowind."
homepage = "https://www.nexusmods.com/morrowind/mods/51009?tab=files"
repository = "https://github.com/jhaakma/crafting-framework"
authors = [ "Merlord",]
version = "1.16.0"

[dependencies]
assets = [ "MWSE/mods/CraftingFramework", "Meshes/craftingFramework", "Textures/craftingFramework", "Sound/craftingFramework",]

[dependencies.mwse]
buildnumber = 3066

[dependencies.mge-xe]
version = ">=0.15.0"

[tools.mwse]
lua-mod = "CraftingFramework"
